# **Chapter 2 : Coding Attention Mechanisms**


### **2.1 Attending to different parts of the input with self-attention**

### 2.1.1 A simple self-attention mechanism without trainable weights

In [1]:
import torch


inputs = torch.tensor(
    [[0.43, 0.15, 0.89], # Yours (x^1)
     [0.55, 0.87, 0.66], # journey (x^2)
     [0.57, 0.85, 0.64], # starts (x^3)
     [0.22, 0.58, 0.33], # with (x^4)
     [0.77, 0.25, 0.10], # one (x^5)
     [0.05, 0.80, 0.55]] # step (x^6)
)

In [2]:
input_query = inputs[1]
input_query

tensor([0.5500, 0.8700, 0.6600])

In [3]:
input_1 = inputs[0]
input_1

tensor([0.4300, 0.1500, 0.8900])

In [4]:
# lets do the dot product between input_query and input_1 using PyTorch

torch.dot(input_query, input_1)

tensor(0.9544)

In [9]:
# we can do this for all the inputs at once using for loop
"""
res = 0.
i = 0

for idx, ele in enumerate(inputs[i]):
        res += inputs[i][idx] * input_query[idx]
res    
""" 
# Alternate

i = 3

res =  torch.dot(inputs[i], input_query)
res

tensor(0.8434)

In [10]:
torch.empty(inputs.shape[0])

tensor([0., 0., 0., 0., 0., 0.])

In [14]:

query = inputs[1]  # 2nd input token is the query 
"""
attn_score_2 = torch.empty(inputs.shape[0])  # to store attention scores
for i in range(inputs.shape[0]):
    attn_score_2[i] = torch.dot(inputs[i], query)
attn_score_2
"""
# we do it to all the inputs at once using matrix multiplication
attn_score_2 = torch.matmul(inputs, query)
attn_score_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])